services:
  boomer:
    image: boomer-app:latest
    platform: linux/arm64
    container_name: boomer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
